cc_library(
    name = "framework",
    srcs = [
        "basic_types.hpp",
        "board.hpp",
        "display.hpp",
        "fen_lib.hpp",
        "legal_move.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/shared",
    ],
)
