name: Checker Tasks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '5.3.0'
      - name: Check Formats
        run: ./run_format.sh
      - name: Build and Test
        run: ./run_tests.sh
